// Menu images are served from /public/menu/<slug>.jpg (Vite serves /public at the site root).
// Drop the real photos in with these exact filenames and they load automatically.
// Until a file exists, the UI shows a branded "photo coming soon" fallback tile.
// See public/menu/README.md for the full list.

export const menuItems = [
  // --- BURGERS ---
  {
    id: 1,
    name: "Chicken Burger",
    category: "Burgers",
    price: 85,
    bestseller: true,
    description: "Crispy flame-grilled chicken fillet, fresh veggies, and our special Delpha sauce.",
    image: "/menu/chicken-burger.jpg",
  },
  {
    id: 2,
    name: "Squad Goals",
    category: "Burgers",
    price: 69,
    bestseller: true,
    description: "Double the beef, double the cheese, double the satisfaction.",
    image: "/menu/squad-goals.jpg",
  },
  {
    id: 3,
    name: "Beshies",
    category: "Burgers",
    price: 109,
    bestseller: false,
    description: "Savory mushrooms and crispy bacon strips on a juicy beef patty.",
    image: "/menu/beshies.jpg",
  },
  {
    id: 4,
    name: "Burger and Bacon",
    category: "Burgers",
    price: 75,
    bestseller: false,
    description: "Smoky bacon strips stacked on a juicy beef patty with melted cheese.",
    image: "/menu/burger-and-bacon.jpg",
  },
  {
    id: 5,
    name: "Haranghae",
    category: "Burgers",
    price: 75,
    bestseller: false,
    description: "Infused with smokey hickory barbecue flavor and topped with crisp onion rings.",
    image: "/menu/haranghae.jpg",
  },
  {
    id: 6,
    name: "Piña-Ibig",
    category: "Burgers",
    price: 75,
    bestseller: false,
    description: "Grilled pineapple slice adds a tropical sweetness to our savory beef patty.",
    image: "/menu/pina-ibig.jpg",
  },
  {
    id: 7,
    name: "Burger and Egg",
    category: "Burgers",
    price: 75,
    bestseller: false,
    description: "A juicy beef patty crowned with a runny fried egg. Breakfast, any time.",
    image: "/menu/burger-and-egg.jpg",
  },
  {
    id: 8,
    name: "Adelpha's Monster",
    category: "Burgers",
    price: 199,
    bestseller: true,
    description: "Our largest creation. Triple patties, extra toppings, and major bragging rights.",
    image: "/menu/adelphas-monster.jpg",
  },

  // --- DRINKS ---
  {
    id: 9,
    name: "Classic Vietnamese Coffee",
    category: "Drinks",
    price: 95,
    bestseller: true,
    description: "Strong, dark roast coffee with a perfect balance of sweet condensed milk.",
    image: "/menu/vietnamese-coffee.jpg",
  },
  {
    id: 10,
    name: "Ube Macapuno Milk Tea",
    category: "Drinks",
    price: 115,
    bestseller: true,
    description: "Filipino favorite ube flavors mixed with creamy macapuno coconut bits.",
    image: "/menu/ube-macapuno-milk-tea.jpg",
  },
  {
    id: 11,
    name: "Cookies & Cream Frappe",
    category: "Drinks",
    price: 125,
    bestseller: false,
    description: "Ice-blended treat with crushed dark chocolate cookies and whipped cream.",
    image: "/menu/cookies-cream-frappe.jpg",
  },
  {
    id: 12,
    name: "Signature Dark Cocoa",
    category: "Drinks",
    price: 110,
    bestseller: false,
    description: "Premium rich chocolate for those who love intense cocoa flavors.",
    image: "/menu/dark-cocoa.jpg",
  },
  {
    id: 13,
    name: "Iced Wintermelon Tea",
    category: "Drinks",
    price: 90,
    bestseller: false,
    description: "Refreshing and light melon flavors, perfect for a sunny afternoon.",
    image: "/menu/wintermelon-tea.jpg",
  },

  // --- SNACKS & OTHERS ---
  {
    id: 14,
    name: "Loaded Meaty Fries",
    category: "Snacks",
    price: 120,
    bestseller: true,
    description: "Crispy fries topped with savory ground beef, cheese sauce, and special dressing.",
    image: "/menu/loaded-meaty-fries.jpg",
  },
  {
    id: 15,
    name: "Cheesy Tortilla Nachos",
    category: "Snacks",
    price: 110,
    bestseller: false,
    description: "Crunchy corn chips with generous cheese drizzle and savory meat sauce.",
    image: "/menu/cheesy-nachos.jpg",
  },
  {
    id: 16,
    name: "Buffalo Chicken Wings",
    category: "Snacks",
    price: 165,
    bestseller: false,
    description: "Perfectly seasoned wings tossed in our signature buffalo glaze.",
    image: "/menu/buffalo-wings.jpg",
  },
  {
    id: 17,
    name: "Delpha's Pasta Special",
    category: "Combos",
    price: 140,
    bestseller: false,
    description: "Rich, savory meat-sauce pasta served with buttery garlic bread.",
    image: "/menu/pasta-special.jpg",
  },
  {
    id: 18,
    name: "Signature Pancakes",
    category: "Pastries",
    price: 95,
    bestseller: false,
    description: "Fluffy, golden pancakes served with butter and premium syrup.",
    image: "/menu/pancakes.jpg",
  },
  {
    id: 19,
    name: "Classic Clubhouse Sandwich",
    category: "Snacks",
    price: 130,
    bestseller: false,
    description: "Fresh ham, cheese, and egg layers in toasted bread. A filling classic.",
    image: "/menu/clubhouse-sandwich.jpg",
  },
  {
    id: 20,
    name: "Breakfast Platter",
    category: "Combos",
    price: 180,
    bestseller: false,
    description: "Everything you need for a great morning: eggs, bacon, toast, and fresh fruit.",
    image: "/menu/breakfast-platter.jpg",
  },
  {
    id: 21,
    name: "Delpha's Pasta Supreme",
    category: "Combos",
    price: 155,
    bestseller: false,
    description: "Our signature pasta recipe with extra creamy sauce and premium toppings.",
    image: "/menu/pasta-supreme.jpg",
  },
  {
    id: 22,
    name: "Overloaded Burger Meal",
    category: "Combos",
    price: 220,
    bestseller: true,
    description: "The complete Adelpha's experience in one satisfying platter.",
    image: "/menu/overloaded-burger-meal.jpg",
  },
];

export const reviews = [
  { id: 1, name: "King Villanueva", rating: 5, date: "a year ago", text: "Foods are very delicious. Whenever I go there I always order my favorites." },
  { id: 2, name: "Arjijiii", rating: 5, date: "a year ago", text: "One of the best hangout spots here in Partido. Affordable food and drinks that satisfy every craving." },
  { id: 3, name: "zeth borrega", rating: 5, date: "2 years ago", text: "Foods are affordable and yummy." },
];
